<a href="https://colab.research.google.com/github/asolnn2a8/evolution_of_species/blob/master/evolution_of_species.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importar y configurar repositorio `evolution_of_species`

Estas celdas es para importar la librería desde GitHub y que se mantenga actualizado. Hay que descomentar las líneas
 si se utiliza desde google colab.

In [1]:
# !git clone https://github.com/asolnn2a8/evolution_of_species.git
# %cd evolution_of_species

In [2]:
# !git pull origin master

In [3]:
# !pip install -r requirements.txt

In [4]:
# !python setup.py install

# Importaciones

In [5]:
from perthame_edp.model.solver import solve_perthame
import numpy as np

x_lims = None  # (-4, 5)
y_lims = (-1, 2)
N = 100  # None  # 100
M = 110
dt = None  # 0.02
T = 120

CONFIG_LIMITES = {
    "x_lims": x_lims,
    "y_lims": y_lims,
    "N": N,
    "M": M,
    "dt": dt,
    "T": T
}

M_1_CONST, M_2_CONST = 0.5, 1.
EPS = 0.001
SIG_K, SIG_IN = 0.6, 1.
R_CONST = 1.
M_IN = 3.
U_MAX, MU_U, SIG_U = 1., 0.25, 1.
R_MAX, MU_R, SIG_R = 5., -0.25, 1.


def K(x, y, sig_K=SIG_K) -> float:
    num = np.exp(- (x - y) ** 2 / (2 * sig_K ** 2))
    den = sig_K * np.sqrt(2 * np.pi)
    return num / den


def R_in(y, M_in=M_IN, sig_in=SIG_IN) -> float:
    num = M_in * np.exp(- y ** 2 / (2 * sig_in ** 2))
    den = sig_in * np.sqrt(2 * np.pi)
    return num / den


def m_1(x) -> float:
    return M_1_CONST


def m_2(x) -> float:
    return M_2_CONST


def r(x) -> float:
    return R_CONST


# Distribuciones Gaussianas
def u_0(x, u_max=U_MAX, mu_u=MU_U, sig_u=SIG_U) -> float:
    num = u_max * np.exp(- (x - mu_u) ** 2 / (2 * sig_u ** 2))
    den = sig_u * np.sqrt(2 * np.pi)
    return num / den


def R_0(y, R_max=R_MAX, mu_R=MU_R, sig_R=SIG_R) -> float:
    num = R_max * np.exp(- (y - mu_R) ** 2 / (2 * sig_R ** 2))
    den = sig_R * np.sqrt(2 * np.pi)
    return num / den


CONFIG_LIMITES["x_lims"] = (0, 1)

u, R = solve_perthame(u_0, R_0, r, R_in, m_1, m_2, K, EPS, **CONFIG_LIMITES)
print(u)
print(R)

SolverU(
  N=100, M=110, T=120,
  x_lims=(0, 1), y_lims=(-1, 2), T_max=1.20
  shape=(121, 102), matrix=
  [[0.18264909 0.18947448 0.19638159 ... 0.09556079 0.09084055 0.08627732]
   [0.18264909 0.19159022 0.19857051 ... 0.0960312  0.09128049 0.08627732]
   [0.18264909 0.19224571 0.19946488 ... 0.09636023 0.09155007 0.08627732]
   ...
   [0.18264909 0.22576991 0.26231015 ... 0.11932634 0.10384914 0.08627732]
   [0.18264909 0.22599353 0.26275637 ... 0.11948316 0.10392733 0.08627732]
   [0.18264909 0.22621689 0.26320217 ... 0.11963973 0.10400538 0.08627732]]
)
SolverRMethod2(
  N=100, M=110, T=120,
  x_lims=(0, 1), y_lims=(-1, 2), T_max=1.20
  shape=(121, 112), matrix=
  [[1.50568716 1.5359582  1.56569372 ... 0.17896054 0.16858671 0.15869826]
   [1.18006912 1.17839552 1.17650771 ... 0.72978047 0.72415568 0.7184537 ]
   [1.17999953 1.17831932 1.17642444 ... 0.72974604 0.72412467 0.71842583]
   ...
   [1.17083785 1.16828865 1.16546638 ... 0.72523972 0.72006633 0.71477852]
   [1.17074881 1.1